/**
 * Canonical Polish URL paths for the application.
 */
import { KONTO_DOKUMENTY_PATH } from './konto-tabs';
import { buildKonkursPath } from './listing/konkurs-slug';

export const routes = {
  home: '/',
  logowanie: '/logowanie',
  rejestracja: '/rejestracja',
  rejestracjaWyborWeryfikacji: '/rejestracja/wybor-weryfikacji',
  zapomnianeHaslo: '/zapomniane-haslo',
  konto: '/konto',
  wiadomosci: '/wiadomosci',
  zapisaneZgloszenia: '/zapisane-zgloszenia',
  wykonawcy: '/wykonawcy',
  zarzadcy: '/zarzadcy',
  /** Public listing URL. Pass title for Allegro-style slug (OPD-162). */
  konkurs: (id: string, title?: string | null) => buildKonkursPath(id, title),
  wykonawca: (id: string) => `/wykonawcy/${id}` as const,
  zarzadca: (id: string) => `/zarzadcy/${id}` as const,
  dodajKonkurs: '/dodaj-konkurs',
  dodajKonkursEdycja: (id: string) => `/dodaj-konkurs/${id}` as const,
  dodajPrzetarg: '/dodaj-przetarg',
  dodajPrzetargEdycja: (id: string) => `/dodaj-przetarg/${id}` as const,
  tworzeniePrzetargu: '/tworzenie-przetargu',
  wyborTypuKonkursu: '/wybor-typu-konkursu',
  wyborTypuKonta: '/wybor-typu-konta',
  uzupelnianieProfilu: '/uzupelnianie-profilu',
  weryfikacja: '/weryfikacja',
  powitanie: '/powitanie',
  samouczek: '/samouczek',
  wdrozenie: '/wdrozenie',
  konsultacjaEksperta: '/konsultacja-eksperta',
  regulamin: '/regulamin',
  politykaPrywatnosci: '/polityka-prywatnosci',
  ustawieniaPlikowCookie: '/ustawienia-plikow-cookie',
  oNas: '/o-nas',
  kontakt: '/kontakt',
  aktualnosci: '/aktualnosci',
  coNowego: '/co-nowego',
  faq: '/faq',
  kategorieUslug: '/kategorie-uslug',
  pomocDlaZarzadcow: '/pomoc-dla-zarzadcow',
  pomocDlaWykonawcow: '/pomoc-dla-wykonawcow',
  dlaWspolnot: '/dla-wspolnot',
  dlaWykonawcow: '/dla-wykonawcow',
  panelWykonawcy: '/panel-wykonawcy',
  panelWykonawcyAplikacje: '/panel-wykonawcy/aplikacje',
  panelWykonawcyPanel: '/panel-wykonawcy/panel',
  panelWykonawcyUlubione: '/panel-wykonawcy/ulubione',
  panelWykonawcyOceny: '/panel-wykonawcy/oceny',
  panelWykonawcyCennik: '/panel-wykonawcy/cennik',
  panelWykonawcyProjekty: '/panel-wykonawcy/projekty',
  panelWykonawcyZamowienia: '/panel-wykonawcy/zamowienia',
  panelZarzadcy: '/panel-zarzadcy',
  panelZarzadcyWykonawcy: '/panel-zarzadcy/wykonawcy',
  panelZarzadcyPrzetargi: '/panel-zarzadcy/przetargi',
  panelZarzadcyKonkursy: '/panel-zarzadcy/konkursy',
  panelZarzadcyKonkursAplikacje: (id: string) =>
    `/panel-zarzadcy/konkursy/${id}/aplikacje` as const,
  panelZarzadcyZgloszenia: '/panel-zarzadcy/zgloszenia',
  panelZarzadcyZamowienia: '/panel-zarzadcy/zamowienia',
  panelZarzadcyOcena: '/panel-zarzadcy/ocena',
  /** @deprecated Use panelZarzadcyOcena */
  panelZarzadcyOcenaZgloszen: '/panel-zarzadcy/ocena',
  administracja: '/administracja',
  administracjaWeryfikacja: '/administracja/weryfikacja',
  administracjaWeryfikacjaUzytkownik: (userId: string) =>
    `/administracja/weryfikacja/${userId}` as const,
  administracjaUstawienia: '/administracja/ustawienia',
  administracjaOferty: '/administracja/oferty',
  administracjaZgloszenia: '/administracja/zgloszenia',
  authAktualizacjaHasla: '/auth/aktualizacja-hasla',
  kontoDokumenty: KONTO_DOKUMENTY_PATH,
} as const

export type AppRoute = (typeof routes)[keyof typeof routes]
